# Generated by Django 6.0.1 on 2026-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], max_length=10),
        ),
    ]
